### ISSUE TITLE
Append from unfinished simulation

### ISSUE THREAD

**Issue by btam125** [pablo-arantes/making-it-rain#10]
Hi, 

Thank you for the software. Currently, I have a question regarding the way of simulation. As I understood that the "make it rain" try to go around the limits of 12h/24h by having the stride time and number of strides, however, I was wondering why not use the restart function within gromacs i.e. "gmx mdrun -cpi state.cpt" during the simulation process? Currently, I keep getting the problem of the simulation stopped at 1.9 ns (and the stride time is 2 ns), then the next restart starts from the beginning of that simulation again. Thank you very much if you can clarify that for me.

Best,

Ben

**Comment by pablo-arantes** [comment]
Hi @btam125 

Thank you for your contact. Regarding your issue, this is OpenMM problem. We don't have an option to use the cpt file to continue the simulation, as Gromacs, on OpenMM engine. We didn't change the OpenMM core code. That's up to the OpenMM developers. 
The best scenario for you here is to reduce the stride time, for example 0.5 or 1 ns. Thus, you will lose only a small part of your simulation and will be able to continue it.

I hope it helps.

Thank you.

Best,

Pablo
