### ISSUE TITLE
Having issue with Ramachandran plot

### ISSUE THREAD

**Issue by xeryan** [pablo-arantes/making-it-rain#11]
Sorry I am new to colab, I was not sure how to troubleshoot this issue. Can you help me on this? The colab i used is AlphaFold2+MD
The error i get is NameError: name 'inp' is not defined. I use the amino acid sequence as input and left everything on default.

![image](https://user-images.githubusercontent.com/96103146/145942797-eed19971-d532-4b7e-b404-e8b2111cc44b.png)

**Comment by pablo-arantes** [comment]
Hi @xeryan,

Thank you for your feedback. 
Regarding your issue, I tried here and everything is working well for me. Have you ever run all the steps before? And did it work well? Don't forget that we are using a notebook, so you should run each step in the same session. Some important variables are defined in the previous cells, and the current cell (Ramachandran plot) is using those variables to run the code.
It seems to me that the code is not finding your input. In this cell, your input should be your AlphaFold2 structure built in the previous cells. 
I hope it helps.

Please, let me know if you have any questions.

Thank you.

Best,

Pablo

**Comment by xeryan** [comment]
Hello,

Thank you for the prompt reply.. 
I had run all the step before it and it work wells. The AlphaFold2 section did generate the protein models for me. Everything was in the same session. Is it related to the google drive? Should I create another folder in my personal drive for this notebook?
![image](https://user-images.githubusercontent.com/96103146/146149945-70746bad-852a-4297-8ca6-65c73ba810fa.png)

**Comment by pablo-arantes** [comment]
Hi @xeryan,

Are you running the Ramachandran Cell in the same session? I mean, did you disconnect and connect again after AlphaFold2 finished your model? 
Because you should run in the same session. If you disconnect, all your variables will be lost, and you should run from the beginning again. 

Let me know if this is the case. 

Thank you.

Best,

Pablo

**Comment by xeryan** [comment]
Hello,

Sorry for the late reply. I have ran the Ramachandran Cell in the same session, I also tried to use stable internet connection to run the colab notebook. I didn't disconnect after AlphaFold2 finished the model. Can you guide me in the troubleshooting? Attached is the screenshot I obtained after I rerun the colab notebook with stable internet connection. Thank you for your time.
![image](https://user-images.githubusercontent.com/96103146/147061119-2f85eb9f-6c72-4400-848c-2a2fb2330969.png)
