### ISSUE TITLE
Protein_2ligands.ipynb ff.Minimize error

### ISSUE THREAD

**Issue by hajnal-adam** [pablo-arantes/making-it-rain#120]
Hi!
It seems that Protein_2ligands.ipynb doesn't work at the moment. But as I was searching in the previous issues, I've seen that issue#78 has already mentioned the following error:
>[<ipython-input-18-af86a6cca64f>](https://localhost:8080/#) in minimize_ligand_charge(input, output)
     86         if (a.GetAtomicNum() > 1):
     87             ff.MMFFAddPositionConstraint(a.GetIdx(), 0, 1.e4)
---> 88     ff.Minimize(maxIts=1000)
     89     charge_mol = Chem.rdPartialCharges.ComputeGasteigerCharges(hmol)
     90     charge = Chem.GetFormalCharge(hmol)

>Invariant Violation
bad direction in linearSearch
Violation occurred on line 240 in file /home/conda/feedstock_root/build_artifacts/rdkit-meta_1722844818947/work/Code/Numerics/Optimizer/BFGSOpt.h
Failed Expression: status >= 0

...which comes from an issue with protonation via RDkit. However, in Protein_2ligands.ipynb even if I submit the already protonated ligands, I always get this error.
Also in the Protein_2ligands.ipynb notebook the Add_ligand_hydrogens ["Yes", "No"] is not visible to avoid this.

Is there a way to overcome this? Thanks in advance!

**Comment by pablo-arantes** [comment]
Hi,

The 2ligands notebook is an old notebook and we are not updating anymore. That is the reason you cannot find the notebook in the main list of the site. You can try modify by yourself changing the code following the protein_ligand notebook. 

Sorry for that.

Best,

Pablo
