### ISSUE TITLE
Protein_ligand.ipynb: Error when providing input files

### ISSUE THREAD

**Issue by hajnal-adam** [pablo-arantes/making-it-rain#121]
Hi!
For some reason, in the Protein_ligand.ipynb notebook whenever I submit any of my interested ligands in their accurately protonated form (also selecting "No" at Add_ligand_hydrogens), the cells runs and ends with an >ERROR: Check your inputs!
I've tried protonating my ligands with PyMol and with UCSF Chimera as well, (ran a DockPrep on my protein as well once) but always the same result.
![Screenshot 2024-10-29 08 24 34](https://github.com/user-attachments/assets/f0fcfb12-76d5-464c-82f7-5d22a403c541)
Any ideas what am I doing wrong? I attached my ligand file, but I don't see any issue with it compared to the example ligand.
[GSH1.zip](https://github.com/user-attachments/files/17553150/GSH1.zip)
Please, if you have any idea what goes wrong all the time, let me know! Thanks in advance.

**Comment by pablo-arantes** [comment]
Hi,

Did you check the charge of your ligand with the respective protonation? Because, I suspect your desire protonation state has non zero charge and that is the issue when you run the cell. 

Thank you.

Best,

Pablo

**Comment by pablo-arantes** [comment]
BTW, I've found an issue in the code. I've fixed, please, try again and let me know.

**Comment by hajnal-adam** [comment]
Hey, I was about to ask if you have changed anything or not, since now the topology creation was succesful. So, great news, and thanks again for your hard work and helpfulness! Very much appreciated! 🙌
