### ISSUE TITLE
stride_time_ps is not defined 

### ISSUE THREAD

**Issue by christos-efthymiou** [pablo-arantes/making-it-rain#13]
I am trying to use the AMBER notebook (https://colab.research.google.com/github/pablo-arantes/Making-it-rain/blob/main/Amber.ipynb) to run a simulation on the PDB file 2XQW. I have followed the instructions throughout the notebook, but when I tried to run the Concatenate and Align Trajectory cell, I got the following error: 

![image](https://user-images.githubusercontent.com/97161093/156669004-d67708ad-04f7-47f9-ae1f-fa110e63ddd1.png)

My runtime disconnected after the "Runs a Production MD simulation (NPT ensemble) after equilibration" step, so I am not sure if this has something to do with the error.

**Comment by pablo-arantes** [comment]
Hi @christos-efthymiou 

Thank you for your message. Regarding your error, when you disconnect you should run again the first cell where you select your PDB ID/Google_Drive_Path and the **_Running a Production MD simulation_** cells (the options should be the same that you used before, Google_Drive_Path, Number_of_strides, stride_time and so on). Thereby, the script will recognize your files in your Google Drive folder, and it will not run again the MD. As we are using notebook environment, some variables are declared in other cells. In your case, the variable **stride_time_ps** is declared in the previous cell (**Runs a Production MD simulation (NPT ensemble) after equilibration**).  

I hope it helps. Please, let me know if you have more questions.

Thank you.

Best regards,

Pablo
