### ISSUE TITLE
CHARMM_GUI ERROR

### ISSUE THREAD

**Issue by TMoahanty** [pablo-arantes/making-it-rain#14]
While running Equilibration MD simulation (NPT ensemble), I faced some error. I request you to please guide in resolving the issue. I am hereby copying the error from my notebook. 
> Simulation details:

	Job name = /content/drive/MyDrive/MD/NOD1_equil
	Coordinate file = /content/drive/MyDrive/MD/step3_pbcsetup.crd
	PDB file = /content/drive/MyDrive/MD/step3_pbcsetup.pdb
	Topology file = /content/drive/MyDrive/MD/step3_pbcsetup.psf
	Force Field files = ()

	Simulation_time = 100.0 ps
	Integration timestep = 2 fs
	Total number of steps = 50000

	Save coordinates each 100 ps
	Print in log file each 10 ps

	Temperature = 298.0 K
	Pressure = 1.0 bar

> Setting the system:

	- Reading topology and structure file...
	- Setting box (using user's information)...
	- Creating system and setting parameters...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.7/site-packages/openmm/app/charmmpsffile.py](https://localhost:8080/#) in loadParameters(self, parmset)
    618                 else:
--> 619                     atype = parmset.atom_types_str[atom.attype]
    620             except KeyError:

KeyError: 'NH3'

During handling of the above exception, another exception occurred:

MissingParameter                          Traceback (most recent call last)
2 frames
[<ipython-input-8-bc71fe4868d0>](https://localhost:8080/#) in <module>()
    164 
    165 print("\t- Creating system and setting parameters...")
--> 166 system = psf.createSystem(charmm_params, nonbondedMethod=PME, nonbondedCutoff=1.2*nanometers, switchDistance=1.0*nanometer, ewaldErrorTolerance = 0.0005, constraints=HBonds)
    167 
    168 print("\t- Applying restraints. Force Constant = " + str(Force_constant) + "kJ/mol")

[/usr/local/lib/python3.7/site-packages/openmm/app/charmmpsffile.py](https://localhost:8080/#) in createSystem(self, params, nonbondedMethod, nonbondedCutoff, switchDistance, constraints, rigidWater, implicitSolvent, implicitSolventKappa, implicitSolventSaltConc, temperature, soluteDielectric, solventDielectric, removeCMMotion, hydrogenMass, ewaldErrorTolerance, flexibleConstraints, verbose, gbsaModel, drudeMass)
    872         """
    873         # Load the parameter set
--> 874         self.loadParameters(params)
    875         hasbox = self.topology.getUnitCellDimensions() is not None
    876         # Check GB input parameters

[/usr/local/lib/python3.7/site-packages/openmm/app/charmmpsffile.py](https://localhost:8080/#) in loadParameters(self, parmset)
    620             except KeyError:
    621                 raise MissingParameter('Could not find atom type for %s' %
--> 622                                        atom.attype)
    623             atom.type = atype
    624             # Change to string attype to look up the rest of the parameters

MissingParameter: Could not find atom type for NH3

**Comment by mdpoleto** [comment]
@TMoahanty this line below makes me think that you are not loading the force field files (toppar.str) to provide the parameters assigned to the topology specified at the .psf file. 

`Force Field files = ()`


Can you double check if you actually defined the correct pathway for the toppar.str file? You can find more details about how to load it in the notebook itself.

**Comment by mdpoleto** [comment]
@TMoahanty there is an entire section in the notebook explaining how to load the input files such as .psf, .crd and the toppar.str file. Note that if your toppar.str file was generated by CHARMM-GUI, you might need to fix the pathways for the force field files (.rtf, .prm and .str files) defined inside the toppar.str file. This is also mentioned in the notebook.

![image](https://user-images.githubusercontent.com/22683331/160628481-9c812159-795f-43ee-97bc-e699eb7adf23.png)

**Comment by TMoahanty** [comment]
@mdpoleto I am still facing some issues while executing the code:
CharmmFileError: [Errno 2] No such file or directory: '/content/drive/MyDrive/MDopen read card unit 10 name toppar/top_all36_prot.rtf'

**Comment by TMoahanty** [comment]
@mdpoleto Another error i faced while installing libraries:-
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "entry_point.py", line 76, in <module>
  File "tarfile.py", line 2036, in extractall
  File "tarfile.py", line 2077, in extract
  File "tarfile.py", line 2150, in _extract_member
  File "tarfile.py", line 2199, in makefile
  File "tarfile.py", line 247, in copyfileobj
  File "tarfile.py", line 521, in read
  File "tarfile.py", line 549, in _read
KeyboardInterrupt
[5366] Failed to execute script entry_point
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 384, in wait_result_broken_or_wakeup
  File "multiprocessing/connection.py", line 256, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 608, in result_iterator
  File "concurrent/futures/_base.py", line 445, in result
  File "concurrent/futures/_base.py", line 390, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[5373] Failed to execute script entry_point

**Comment by pablo-arantes** [comment]
Hi @TMoahanty ,

Did you check the tutorial files (https://github.com/pablo-arantes/making-it-rain/tree/main/Colab_OpenMM_CHARMM)? There you can check how the files and pathways should be in your CHARMM-GUI outputs. 
You should have in your Google Drive folder the following files: **PSF, CRD, PDB, toppar.str and toppar folder** (check the image below). Please, don't forget to put the correct pathway on **Google_Drive_Path** option in the notebook. 
For example, if my folder on Google Drive is **Pablo_MD**, My pathway will be: **/content/drive/MyDrive/Pablo_MD**
Inside the Pablo_MD folder I should have all the files (PSF, CRD, PDB, toppar.str and toppar folder).

<img width="282" alt="image" src="https://user-images.githubusercontent.com/35934150/160726055-72b54b92-3084-42de-83c9-4aa109bd3bf5.png">

Regarding your second issue, this usually happens when you already have the libraries installed and is trying to install again. Just disconnect and connect again.

Thank you.

**Comment by TMoahanty** [comment]
Hi @pablo-arantes 
Thank you so much for your guidance, I was able to run the above codes successfully. 
But I faced some issues for which I request you to please guide me on that:- 
1. How can I run 100 ns as right now I am able to run 2 ns per day?
2. Although I had run the MD production for 10 ns but before runtime was exhausted 2ns was completed but no file  was created in my Drive till then. How can I save it ? 
Regards

**Comment by TMoahanty** [comment]
Hi @mdpoleto and @pablo-arantes !
Thank you so much for guidance as I have been able to run 18 ns production file till now. But while viewing the trajectory and PCA file I came across some error. So i request you to please guide on it.

ValueError Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_axes.py](https://localhost:8080/#) in _parse_scatter_color_args(c, edgecolors, kwargs, xsize, get_next_color_func)
4238 try: # Is 'c' acceptable as PathCollection facecolors?
-> 4239 colors = mcolors.to_rgba_array(c)
4240 except ValueError:

9 frames
ValueError: Invalid RGBA argument: 0.0

During handling of the above exception, another exception occurred:

ValueError Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_axes.py](https://localhost:8080/#) in _parse_scatter_color_args(c, edgecolors, kwargs, xsize, get_next_color_func)
4240 except ValueError:
4241 if not valid_shape:
-> 4242 raise invalid_shape_exception(c.size, xsize)
4243 # Both the mapping and the RGBA conversion failed: pretty
4244 # severe failure => one may appreciate a verbose feedback.

ValueError: 'c' argument has 36 elements, which is inconsistent with 'x' and 'y' with size 624.

**Comment by mdpoleto** [comment]
@TMoahanty you ran 18ns but you have only 9 frames being analyzed. That does not sound about right. Your errors seem to be from matplotlib, which is only plotting the PCA and not calculating it. Checking if your PCA calculation is indeed making an output file or array would be your first step.
