### ISSUE TITLE
Amber Error 

### ISSUE THREAD

**Issue by TMoahanty** [pablo-arantes/making-it-rain#15]
Hi @mdpoleto and @pablo-arantes !
Thank you so much for guidance as I have been able to run 18 ns production file till now. But while viewing the trajectory and PCA file I came across some error. So i request you to please guide on it. 

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_axes.py](https://localhost:8080/#) in _parse_scatter_color_args(c, edgecolors, kwargs, xsize, get_next_color_func)
   4238             try:  # Is 'c' acceptable as PathCollection facecolors?
-> 4239                 colors = mcolors.to_rgba_array(c)
   4240             except ValueError:

9 frames
ValueError: Invalid RGBA argument: 0.0

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_axes.py](https://localhost:8080/#) in _parse_scatter_color_args(c, edgecolors, kwargs, xsize, get_next_color_func)
   4240             except ValueError:
   4241                 if not valid_shape:
-> 4242                     raise invalid_shape_exception(c.size, xsize)
   4243                 # Both the mapping *and* the RGBA conversion failed: pretty
   4244                 # severe failure => one may appreciate a verbose feedback.

ValueError: 'c' argument has 36 elements, which is inconsistent with 'x' and 'y' with size 624.

**Comment by mdpoleto** [comment]
This question was posted twice.
