### ISSUE TITLE
Amber error

### ISSUE THREAD

**Issue by bpsg048** [pablo-arantes/making-it-rain#16]
@mdpoleto 
Hi @mdpoleto 
while doing PCA analysis, it's showing an error. I have attached a snapshot of the error. Thank you.
![00000033](https://user-images.githubusercontent.com/103850581/163686709-4be6403b-a82e-42be-9242-10466934547e.JPG)

**Comment by mdpoleto** [comment]
We can not reproduce this error just with the snapshot, mainly because it seems to be an issue with how matplotlib is handling the variable `c`. Please provide us more details of what you did before getting the error. In special, if the connection was lost between any of the steps.
