### ISSUE TITLE
name 'vol' is not defined

### ISSUE THREAD

**Issue by masoudrezaei** [pablo-arantes/making-it-rain#17]
Hi.
Thank you for your great repository. I have used AMBER notebook several times in the past few days, and it worked fine. But now, when I even try the example PDB ID file 1AKI, it returns an error about the vol of the file.
Name 'vol' is not defined.
Please help me to fix this error

**Comment by masoudrezaei** [comment]
Many thanks!
now it works fine.
wish the best!

**Comment by pablo-arantes** [comment]
Hi @masoudrezaei,

I have seen you reopened the issue, I checked the notebook and everything is working fine. Any other issue? 

Thank you.

Best,

Pablo

**Comment by JMdeSteAgathe** [comment]
Hi,
I encounter the same issue, but with the `Protein_ligand` notebook
Thanks!
Jean-Madeleine
