### ISSUE TITLE
Unable to open output file

### ISSUE THREAD

**Issue by avinashkarkada** [pablo-arantes/making-it-rain#22]
Hello.
1. How do I visualize the output of the simulation?. I am unable to open the output xtc, pdb, dcd or trr.
2. Is there any way to generate .tpr files?

Thank you

**Comment by cpedebos** [comment]
Hello,

1. You can visualize the trajectory using VMD. You need to load both a PDB or GRO file and a trajectory file as well (XTC, DCD, TRR). For more information, refer to the VMD website: https://www.ks.uiuc.edu/Research/vmd/

2. To generate a tpr file, you need to use the Gromacs simulation suite in your local machine. We don't use Gromacs in the notebooks.

Best,
Conrado.

**Comment by avinashkarkada** [comment]
Hey.
Would you please specify what simulation suite is used in the notebook?


Thank you

**Comment by pablo-arantes** [comment]
Hi, 

I strongly recommend that you read the Making it Rain paper (https://pubs.acs.org/doi/10.1021/acs.jcim.1c00998), everything is well explained there.
Regarding your question, in the Making it Rain code we are using OpenMM toolkit for molecular dynamics simulation (https://openmm.org/). 

Pablo

**Comment by avinashkarkada** [comment]
Thank you!
