### ISSUE TITLE
Molecular Simulation on Protein Ligand Complex in Gromacs

### ISSUE THREAD

**Issue by atultiwari** [pablo-arantes/making-it-rain#23]
Hi,

First of all, thank you very much for this awesome work. However, I am only familiar with Gromacs. I see that there is one Gromacs_input file but that uses protein only. I wanted to know how to perform molecular simulation on protein-ligand complex in gromacs by this method.

Thank you

**Comment by pablo-arantes** [comment]
Hi @atultiwari,

Sorry for my late reply.
Regarding your question, If you check the Making it Rain paper (https://pubs.acs.org/doi/10.1021/acs.jcim.1c00998), everything is well explained there. We are not using Gromacs for MD simulations. In the Making it Rain code we are using OpenMM toolkit for molecular dynamics simulation (https://openmm.org/). OpenMM toolkit is able to read the Gromacs format files and proceed with the simulations. 
If you want to run MD simulations of protein-ligand complex, you can use our protein-ligand notebook or our notebook that recognize Gromacs files (https://colab.research.google.com/github/pablo-arantes/making-it-rain/blob/main/Gromacs_inputs.ipynb).

Thank you.

Best,

Pablo

**Comment by atultiwari** [comment]
Hi,

Thank you for your reply. Unfortunately my institute does not provide access to the journal in which the article is published, and I cant afford to purchase the access to article at an individual level.
But my query is well answered in your reply.

Thank you

**Comment by pablo-arantes** [comment]
Hi @atultiwari,

Sorry for that. You can check the preprint (https://chemrxiv.org/engage/chemrxiv/article-details/6116a01f424ea3ed758921a7), is almost the same paper.
I'm closing the issue now.

Thank you.

Best,

Pablo
