### ISSUE TITLE
DCD file does not exist

### ISSUE THREAD

**Issue by dag2225** [pablo-arantes/making-it-rain#27]
Hi! I am trying to use the Amber.ipynb Colab notebook to run a MD simulation on the structure with PDB ID 5cvw.  At the step "Concatenate and align the trajectory", after running everything above it successfully with default settings, I receive the error below:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-20-5b6d9d65b597>](https://localhost:8080/#) in <module>()
     38 ref = [template % int(1)]
     39 
---> 40 u1 = mda.Universe(pdb, flist)
     41 u2 = mda.Universe(pdb, ref)
     42 

5 frames
[/usr/local/lib/python3.7/dist-packages/MDAnalysis/coordinates/DCD.py](https://localhost:8080/#) in __init__(self, filename, convert_units, dt, **kwargs)
    133         super(DCDReader, self).__init__(
    134             filename, convert_units=convert_units, **kwargs)
--> 135         self._file = DCDFile(self.filename)
    136         self.n_atoms = self._file.header['natoms']
    137 

MDAnalysis/lib/formats/libdcd.pyx in MDAnalysis.lib.formats.libdcd.DCDFile.__cinit__()

MDAnalysis/lib/formats/libdcd.pyx in MDAnalysis.lib.formats.libdcd.DCDFile.open()

OSError: DCD file does not exist

__________________________________

I do not know why this is the case, because a file 5cvw_prod_1.dcd has been saved to my Google Drive from the previous cell in the run; can you help me fix this?

**Comment by pablo-arantes** [comment]
Hi @dag2225,

Sorry for my delay. 
Regarding your issue, seems to me that your pathway or your job name is not the same that you used to run. I mean, in the "_Concatenate and align the trajectory_" cell (image attached)  you have the option to put your **Google Drive Path** (where you have your dcd files) and your **Jobname** (should be the same that you have used to run your production step). 
For example, if you used 1AKI_prod as a Jobname in the production step, you should keep the same name for the concatenation step.
![image](https://user-images.githubusercontent.com/35934150/176062159-0453f45e-cb6b-42fa-afa5-083625af89b1.png)

I hope it helps. Please, let me know if you have any question.

Thank you.

Best,

Pablo

**Comment by dag2225** [comment]
Hi Pablo, thanks for the helpful information! I tried this with all the default filled in values relating to 1AKI, but unfortunately it did not fix my problem.  I did also check, and I have a file in /content/drive/MyDrive called "1aki_prod_1.dcd".  Since this file exists, and I checked that the jobname for the production step and concatenation step match,  I am again not sure how to fix the problem.

At the end of the "Runs a Production MD Simulation" cell, I get the output:

> Writing state file (/content/drive/MyDrive/1aki_prod_1.rst)...
> Writing coordinate file (/content/drive/MyDrive/1aki_prod_1.pdb, frame = 200)...
> Finished!

with all the default filled in values kept the same as when I first opened the Colab link.   Attached are screenshots of the files the code I have been able to run from the notebook has generated in my drive.  Hope this additional information is helpful, and we can figure out what is wrong - I appreciate your patience, as I am very new to protein MD simulation :)

![screenshot1](https://user-images.githubusercontent.com/65304967/176329292-afac8f93-83a4-4b45-95b6-8afef11a03ed.png)
![screenshot2](https://user-images.githubusercontent.com/65304967/176329306-31ca2ba4-488d-41be-8fdf-872d283638fd.png)

**Comment by pablo-arantes** [comment]
Hi @dag2225,

Thank you for your feedback. Regarding your error, I think I got it what is the issue. You have only one dcd file in your folder, in other words, you have used only 1 stride in the production options. You should keep the same options in the _Concatenate and align the trajectory_ cell. Follow the picture where I tried, and it worked well for me. 

<img width="642" alt="image" src="https://user-images.githubusercontent.com/35934150/176581641-6d31c62e-688c-4276-8501-db3fab95bb6a.png">

Probably, you are using stride = 2 in this cell, however you only have 1 stride (one dcd file in your folder). I've done a test with stride 2, and I had the same error. 

One tip, when you are going to run and save the files on your Google Drive, please, create a folder in your Drive and save there. I think it is going to help to find and organize all the files created during the simulations.

I hope it helps. Please, let me know if you have any questions.

Thank you.

Best,

Pablo

**Comment by dag2225** [comment]
Hi Pablo, that appears to have solved the problem.  Thank you so much for your continued help!! I am excited to continue exploring how your notebook can be used for my research :)
