### ISSUE TITLE
Simulation accuracy of making it rain pipeline 

### ISSUE THREAD

**Issue by rijuaxt** [pablo-arantes/making-it-rain#28]
I was wondering if you could let me know the simulation accuracy of making it rain pipeline. It turns out that a system which i have simulated has very unexpected data. 

I have used 5000 cycle energy minimization with 2 fs integration time. After 10ns equilibrium simulation, i have run 100ns MD production. However the result is bit weird. I tried increasing minimization cycles too. It doesn’t produce good results though. The same system i have simulated through DESMOND provides me RMSD around 2.5 angstrom 

Force field amber 14 
Tip3P water model,  temp 298K, pressure 1 bar

Please see the attachment and check where the problem is arising  from? 
![rmsd_ca](https://user-images.githubusercontent.com/72547976/177617708-66029d46-ce76-42e6-b159-7911f2f0fa34.png)

**Comment by pablo-arantes** [comment]
Hi @rijuaxt,

Regarding your question, I have some points:

1) Making it rain **IS NOT** a MD engine. We prepare a Jupyter notebook scripts for running Molecular Dynamics simulations using OpenMM engine and AMBER and CHARMM force fields files on Google Colab. So, the accuracy should be related to OpenMM.

2) If you want to compare your obtained data on Making it rain notebooks with previous simulations from other engine, you should use the same parameters: Force Field, water model, box size, temperature, pressure and ions concentrations. Not only that, you should use the same barostat and so on...

3) I don't know which notebook you have been using. For example, if you are using the AMBER notebook (the first one), it works only for protein systems. If you have DNA, small ligand or a specific ion in your protein, the code will remove and keep only the protein for the simulation. It is clear on the notebook : _"This is a Jupyter notebook for running Molecular Dynamics (MD) simulations using OpenMM engine and AMBER force field for PROTEIN systems."_

Please, let me know if you have any question. 

Thank you.

**Comment by rijuaxt** [comment]
I understand. I used protein-ligand colab  notebook from github. My systems
had proteins and ligand.

**Comment by rijuaxt** [comment]
I have used same parameters for comparison.  One point i needed know, which simulation box is used for protein-ligand jupyter Notebook?

**Comment by pablo-arantes** [comment]
Hi @rijuaxt,

If you are using the protein-ligand notebook, it's important to check which force field you have selected for the ligand. Are you using the same force field for the ligand that you used in your previous simulation? 
The simulation box you should define the size in the **Parameters to generate the topology**  cell. For the notebook we are using cubic box, as you can see in the **Show 3D structure** cell.

I hope it helps.

Thank you.
