### ISSUE TITLE
AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'

### ISSUE THREAD

**Issue by pharmozyme-rperez** [pablo-arantes/making-it-rain#29]
Encountered when executing the Run Prediction cell in the AlphaFold2+MD colab.

AttributeError                            Traceback (most recent call last)
[<ipython-input in <module>()
     14     del os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"]
     15 
---> 16 from colabfold.colabfold import plot_protein
     17 from pathlib import Path
     18 import matplotlib.pyplot as plt

7 frames
[/usr/local/lib/python3.7/dist-packages/jax/_src/lax/fft.py] in <module>()
    143 batching.primitive_batchers[fft_p] = fft_batching_rule
    144 if pocketfft:
--> 145   xla.backend_specific_translations['cpu'][fft_p] = pocketfft.pocketfft

**Comment by pablo-arantes** [comment]
Hi @pharmozyme-rperez,

Sorry for the delay.
I've fixed the code. Please, try again and let me know if everything is working fine.

I hope it helps.

Thank you.

Pablo
