### ISSUE TITLE
error running AF2 prediction

### ISSUE THREAD

**Issue by kkorotkov27** [pablo-arantes/making-it-rain#30]
AF2 module gives the following error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-7fa58a4d17b5>](https://localhost:8080/#) in <module>()
     94 import sys
     95 sys.path.append('/usr/local/lib/python3.7/site-packages/')
---> 96 from biopandas.pdb import PandasPdb
     97 import os
     98 import urllib.request

ModuleNotFoundError: No module named 'biopandas'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by pablo-arantes** [comment]
Hi @pharmozyme-rperez,

Sorry for the delay.
I've fixed the code. Please, try again and let me know if everything is working fine.

I hope it helps.

Thank you.

Pablo
