### ISSUE TITLE
Parameters to generate the topology - Making it rain: Cloud-based molecular simulations for everyone

### ISSUE THREAD

**Issue by KAO-KI** [pablo-arantes/making-it-rain#31]
NameError                                 Traceback (most recent call last)
[<ipython-input-6-546d791de995>](https://localhost:8080/#) in <module>()
    157         vol = float(line.split()[1])
    158 
--> 159 vol_lit  = vol * pow(10, -27)
    160 atom_lit = 9.03 * pow(10, 22)
    161 conc = float(Concentration)

NameError: name 'vol' is not defined
![Web capture_26-7-2022_222850_colab research google com](https://user-images.githubusercontent.com/110063041/181106969-2735f27d-1648-4a58-b11b-581434b89883.png)

![Web capture_26-7-2022_222742_colab research google com](https://user-images.githubusercontent.com/110063041/181106044-7609ee1d-9dd4-460d-8736-1b30f9a28cf0.jpeg)

**Comment by ER6RAJY** [comment]
same error

**Comment by pablo-arantes** [comment]
Hi all,

Can you please give more information about the error? Which system are you trying? Did you put the hydrogens in your ligand?  Seems to me the issue is on the ligand topology generation. 
I tried here and everything worked fine for me. Follow the print:

<img width="1387" alt="image" src="https://user-images.githubusercontent.com/35934150/181629714-d5ec9f27-915f-462a-a1ba-49ed1497919f.png">

Thank you.

Best,

Pablo

**Comment by ER6RAJY** [comment]
Hello
Thanksthis is the error message that gives

**Comment by KAO-KI** [comment]
Hello sir,

i use linux LXLE 20.04 Ubuntu based system.
am using my ligand best pose from my docking simulation.
original file was *.pdbqt and converted to *.pdb by using openbabel command line.
my protein was generated ab initio by I-Tesssar server.. and prepared by autodock tool 1.5.7.
the problem occur at this step : the ligand topology generation... i ru the code and then after 4 min it brake and give the error message " name 'vol' is not defined"
i think that the code cant find the variable 'vol' in the scope ... between line 157 and 159.

i want to thank u for your script, its a huge help for all the students.
respectfully.

**Comment by KAO-KI** [comment]
Problem resolved (... Did you put the hydrogens in your ligand? ...) the problem was my ligand.
apologize sir.
