### ISSUE TITLE
Install dependencies - Protein_ligand.ipynb

### ISSUE THREAD

**Issue by KAO-KI** [pablo-arantes/making-it-rain#32]
when i install the dependencies i get this message : 

WARNING:openff.toolkit.utils.toolkit_registry:
![Image 1](https://user-images.githubusercontent.com/110063041/184161323-02808128-bc97-471b-bf1a-bb07c1277312.png)
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
WARNING:root:Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

**Comment by pablo-arantes** [comment]
Hi @KAO-KI,

Did you try to run all the cells? I have tried here and everything worked fine for me. I had the same warning, but this is only a warning on the installation steps. All the necessary libraries are installed correctly.

Thank you.

Pablo

**Comment by KAO-KI** [comment]
Hi Pablo,
yes I followed all the steps, I was afraid it was a mistake, I'll continue my simulation...thank you for your help...it's very reassuring.

Cordially.
