### ISSUE TITLE
How to enter a specific Ligand_isomer to generate a topology file

### ISSUE THREAD

**Issue by Ash1000** [pablo-arantes/making-it-rain#33]
Hello, 
I have a basic question, my ligand generates four isomers. If I am not mistaken, I need to select one of them to generate topology. What character should I mention to pass the step and generate ligand_GAFF.pdb?
Thanks

**Comment by pablo-arantes** [comment]
Hi,

You just need to type the number of your isomer. For example, if you want to select the isomer number 4, Ligand_isomer = 4. 
Follow the print:
<img width="840" alt="image" src="https://user-images.githubusercontent.com/35934150/184258870-8232e87c-fb6a-480d-8c06-05e8be772bad.png">

I hope it helps.

Thank you.

Best,

Pablo

**Comment by Ash1000** [comment]
Thanks, Pablo, I have tried inserting numbers but every time it failed to generate the ligand_gaff.pdb.
cat: /content/drive/MyDrive/1-Mcom/ligand_gaff.pdb: No such file or directory
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-7-4a1181110e17>](https://localhost:8080/#) in <module>()
    157         vol = float(line.split()[1])
    158 
--> 159 vol_lit  = vol * pow(10, -27)
    160 atom_lit = 9.03 * pow(10, 22)
    161 conc = float(Concentration)

NameError: name 'vol' is not defined
