### ISSUE TITLE
Can't Install dependencies

### ISSUE THREAD

**Issue by MuthuBIN** [pablo-arantes/making-it-rain#35]
RuntimeError: This event loop is already running

We have previously run this code successfully. However, we have facing some issues now.
Whenever we tried to install the dependencies we have ended up with RuntimeError.

How to resolve this.

Thank you in advance
![Issue](https://user-images.githubusercontent.com/109590152/184840741-45866233-94d0-4ed7-9289-85b8bacd10ee.PNG)
.

**Comment by quantaosun** [comment]
It happens to me as well. I believe it just happened in the last two days, previously it worked pretty well.

**Comment by quantaosun** [comment]
Just found if run the commands in split cells, it just works. An error I noticed, for the pybel installation, there is an incompatible error. nevertheless, I can go until equilibration simulation as normal, haven't run the rest yet.

**Comment by tahirchohan** [comment]
I am also facing the same issue. My simulation was running fine and suddenly it stoped and from that time I am facing the same issue. Please help to reseolve the issue **SyntaxError: import * only allowed at module level**

**Comment by mateoalpha98** [comment]
> I am also facing the same issue. My simulation was running fine and suddenly it stoped and from that time I am facing the same issue. Please help to reseolve the issue **SyntaxError: import * only allowed at module level**

same problem here mate!
and also from my terminal

python3 openmm.py 
Traceback (most recent call last):
  File "/home/mateoc/Documentos/practiques/tleap_propka/openmm.py", line 1, in <module>
    from openmm.app import *
  File "/home/mateoc/Documentos/practiques/tleap_propka/openmm.py", line 1, in <module>
    from openmm.app import *
ModuleNotFoundError: No module named 'openmm.app'; 'openmm' is not a package

this used to work since last week...

**Comment by pablo-arantes** [comment]
Hi All,

Sorry for my delay. I'm fixing the issue, as soon as it's ready I'll let you know.

Thank you for letting me know about the issue.

Pablo

**Comment by pablo-arantes** [comment]
Hi All,

I have fixed all the issues in the notebooks. Please, try to use again and let me know if everything is working fine.

Thank you.

Best,

Pablo

**Comment by quantaosun** [comment]
Hi Pablo,

It works for me; thanks for your effort to keep this running.
