### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by srs1402** [pablo-arantes/making-it-rain#36]
<img width="881" alt="Screenshot 2022-08-20 at 7 49 01 PM" src="https://user-images.githubusercontent.com/52519729/185744721-caef1c10-912b-4f92-8827-be5eba3e3e6d.png">

**Comment by pablo-arantes** [comment]
Hi @srs1402,

Thank you for letting me know about the issue. I have fixed all the notebooks. Please, try again and let me know if everything is working fine.

Best,

Pablo

**Comment by srs1402** [comment]
Hi @pablo-arantes 

Working fine now, Thanks

Best,

Siddharth
