### ISSUE TITLE
Dynamic simultation using Martini forcefiekd

### ISSUE THREAD

**Issue by Alain-chavanieu** [pablo-arantes/making-it-rain#37]
Hello

This summer we ran several dynamics (openMM/charmm) using your notebook on google colab.
As said in a previous mail, Many thanks for that.
Now, we ll have to run coarse-grained dynamic (Martini 3.0.0) with  a system.top as that one (below) and (e.g.) such /bin

Is there any possibility a google colab notebook will be available in weeks coming , May be there is little interest for that ? However running a dynamic simultation on google colab is very confortable for us (low CPU, no GPU in the lab)

Thank you for your time and help

Alain 

!/bin/csh
#
# Generated by CHARMM-GUI (http://www.charmm-gui.org)
#
# 1) Use Gromacs 5.1 or newer to run these simulations
#

# Minimization
setenv GMX_MAXCONSTRWARN -1
# step4.0 - soft-core minimization
gmx grompp -f step4.0_minimization.mdp -o step4.0_minimization.tpr -c step3_charmm2gmx.pdb -r step3_charmm2gmx.pdb -p system.top -n index.ndx
gmx mdrun -deffnm step4.0_minimization

# step4.1
gmx grompp -f step4.1_minimization.mdp -o step4.1_minimization.tpr -c step4.0_minimization.gro -r step3_charmm2gmx.pdb -p system.top -n index.ndx
gmx mdrun -deffnm step4.1_minimization
unsetenv GMX_MAXCONSTRWARN

# Equilibration
gmx grompp -f step4.2_equilibration.mdp -o step4.2_equilibration.tpr -c step4.1_minimization.gro -r step3_charmm2gmx.pdb -p system.top -n index.ndx
gmx mdrun -deffnm step4.2_equilibration

# Production
gmx grompp -f step5_production.mdp -o step5_production.tpr -c step4.2_equilibration.gro -p system.top -n index.ndx
gmx mdrun -deffnm step5_production

system.top
#include "toppar/martini_v3.0.0.itp"
#include "toppar/martini_v3.0.0_ions_v1.itp"
#include "toppar/martini_v3.0.0_nucleobases_v1.itp"
#include "toppar/martini_v3.0.0_phospholipids_v1.itp"
#include "toppar/martini_v3.0.0_phospholipids_v1_matthieu.itp"
#include "toppar/martini_v3.0.0_small_molecules_v1.itp"
#include "toppar/martini_v3.0.0_solvents_v1.itp"
#include "toppar/martini_v3.0.0_sugars_v1.itp"
#include "p15c2_proa.itp"
#include "p15c2_prob.itp"
#include "p15c2_proc.itp"

[ system ]
; name
Martini system

[ molecules ]
; name        number
PROA 1
PROB 1
PROC 1
W 38366
NA 428
CL 426

![image](https://user-images.githubusercontent.com/103523026/188598066-e243876a-e22c-46bb-a5d3-acea9ecccf41.png)

**Comment by pablo-arantes** [comment]
Hi @Alain-chavanieu,

Sorry for my delay. Unfortunately, it's still not possible to use coarse-grained models (Martini, SIRAH, etc) on OpenMM engine. As our notebooks are using OpenMM engine to run the molecular dynamics simulations, we cannot use coarse-grained models yet. 
One suggestion is installing Gromacs on Google Colab and run your coarse-grained simulations there.
Follow a video where they have shown how to install and run Gromacs on Colab: https://www.youtube.com/watch?v=HDlO13gvgsY&ab_channel=SelfStudy

I hope it helps.

Thank you.

Best,

Pablo

**Comment by Alain-chavanieu** [comment]
Hello 

Thank you for ypur email. I'm teaching at the moment but in weeks coming I certainly watch your video and try some solutions. 
One is using Gromacs on our station but i rather prefer to go for a google colab if I find how to manage. 
The idea behind it 's to propose a rapid optimization of a binding mode of an antibody in contact to a protein. 

Best 

Alain
