### ISSUE TITLE
 Gromacs_inputs 

### ISSUE THREAD

**Issue by cwilliamszf** [pablo-arantes/making-it-rain#38]
I am new to molecular dynamics and I am trying to do some simulations of mutant GPCRs in membranes.  To create a system for your Colab notebook for simulation I used GPCRmodsim to get a short simulation and necessary GROMACS files.  Unfortunately, when I run the simulation, I get the following error:

Too few fields in [ dihedraltypes ] line:     SI   OS    1     0.000       3.766      3

Any help would be appreciated. 

I have included the gro and top files and also for good measure the FF files.
[WTactive.zip](https://github.com/pablo-arantes/making-it-rain/files/9638807/WTactive.zip)
[FFfiles.zip](https://github.com/pablo-arantes/making-it-rain/files/9638808/FFfiles.zip)

**Comment by cwilliamszf** [comment]
Addendum 
here is the screenshot of the error.
![image](https://user-images.githubusercontent.com/46091205/192101383-1e33a3c9-373a-4471-aab7-ea4e606088ea.png)

**Comment by pablo-arantes** [comment]
HI @cwilliamszf,

Sorry for my delay.
Regarding your question, I've checked your files and seems to me that topologies from GPCRmodsim are a little bit different from GROMACS topologies. I believe this is your major issue here.
If you could create the topology directly in GROMACS and try again, it would be better. 
I can understand that GPCRmodsim topologies work well in GROMACS, however we are using OpenMM engine to run MD simulation. With that in mind, OpenMM is very restricted in the file format. 

Sorry for that, I hope you understand.

Thank you.

Best,

Pablo
