### ISSUE TITLE
NameError: name 'mbondi' is not defined

### ISSUE THREAD

**Issue by KAO-KI** [pablo-arantes/making-it-rain#39]
![Screenshot at 2022-10-05 00-51-16](https://user-images.githubusercontent.com/110063041/193945039-b1305134-0d2f-4ebe-a3dc-e425020f0bf3.png)

hello sir,

what is this error?

best regards.

**Comment by pablo-arantes** [comment]
HI @KAO-KI,

Thank you for your contact, I found an error in the code. I just fixed, can you please open the link again and try? 

Thank you.

Best,

Pablo

**Comment by KAO-KI** [comment]
Good afternoon sir,
it's work well, thank you sir,
best regards

chaouki.
