### ISSUE TITLE
RuntimeError: n_atoms = 0

### ISSUE THREAD

**Issue by wildyouth** [pablo-arantes/making-it-rain#4]
Hi @pablo-arantes

I got this issue "RuntimeError: n_atoms = 0: make sure to load correct Topology filename or load supported topology (pdb, amber parm, psf, ...)" for the cell "Runs an Equilibration MD simulation (NPT ensemble)".

I used all the file given by Solution Builder.

![image](https://user-images.githubusercontent.com/92101497/137807335-ebf9470f-adc3-4611-89d3-32ac99ce55e7.png)

Thanks for your response,

Have a nice day.

**Comment by wildyouth** [comment]
Yes, I was trying to run on CHARMM-GUI notebook. I just re-run the notebook and this time it worked perfectly, I don't know what happened. I didn't modify anything on any files.

Thanks for your response.

**Comment by MichaelWedemeyer** [comment]
Hi @pablo-arantes 

I have run into the same problem as above. I am using the tutorial files for the Charmm-Gui notebook, but the Topology file thinks there are no atoms. I've double checked all of the demo files in a text editor and they look fine, so I am not sure what the issue could be. Unfortunately, I've reran the notebook several times with no improvement. Any insight on where the problem may be?

Thanks,
Mike

![image](https://user-images.githubusercontent.com/41838033/138181464-d70853b7-5a0f-4fe6-aaa7-c965e3055e75.png)

**Comment by pablo-arantes** [comment]
Hi @MichaelWedemeyer 

It's weird, I checked all the input files and the notebook. I have run the notebook again, and everything is working fine for me. 

![image](https://user-images.githubusercontent.com/35934150/138221041-1e2257d2-2657-4680-b9ff-50ee33c277a5.png)

Please, check your input files names and your pathway: 

![image](https://user-images.githubusercontent.com/35934150/138221228-066aa03b-b914-474a-bf93-8d1fc37ef202.png)

I'm sending here all the input files in zip format. 

Please,  let me know if it's working.

Thank you.

Pablo.

[Colab_OpenMM_CHARMM.zip](https://github.com/pablo-arantes/making-it-rain/files/7386417/Colab_OpenMM_CHARMM.zip)
