### ISSUE TITLE
Exception ignored in: 'MDAnalysis.lib.formats.libdcd.DCDFile._read_header' OSError: Reading DCD header failed: premature EOF found in DCD file

### ISSUE THREAD

**Issue by marionamujal** [pablo-arantes/making-it-rain#42]
I get the above error using Gromacs input files, I cannot proceed to concatenate and align the trajectory.
OSError: opened empty file. No frames are saved

**Comment by marionamujal** [comment]
I get that error after running using Gromacs input files, I cannot concatenate and align the trajectory

**Comment by pablo-arantes** [comment]
Hi @marionamujal,

Sorry for my delay. Thank you for letting me know about the issue. I will check and back to you.

Best,

Pablo

**Comment by pablo-arantes** [comment]
HI @marionamujal,

I've checked here and everything is working fine for me. Please, check if you are using the same **Google Drive Path, Jobname, Number of strides, stride time and trajectory saved frequency** that you have been used to run your simulation in the previous steps.

Thank you.

Best,

Pablo
