### ISSUE TITLE
Multible GPUs

### ISSUE THREAD

**Issue by mohamedfadlalla** [pablo-arantes/making-it-rain#43]
OpenMM package has support for multiple GPUs is it possible to implement this on making-it-rain, or it's limited by the number of CPUs on colab?
if so what's the minimum number of CPUs to run multiple GPUs?

Thanks in advance :)

**Comment by pablo-arantes** [comment]
Hi @mohamedfadlalla,

Sorry for my delay. As we said in the paper the idea of Making it Rain is _"highlight the usage of a cloud- computing"_ .
For sure, the notebooks can be used locally (https://research.google.com/colaboratory/local-runtimes.html) and then maybe you can implement multiple GPUs and so on.

I hope it helps.

Thank you.

Best,

Pablo
