### ISSUE TITLE
openmm circular import

### ISSUE THREAD

**Issue by kva0987** [pablo-arantes/making-it-rain#44]
Hi,

While it has been working perfect few days ago, I get error messages as below just recently;

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-4-b1b22f26e220>](https://localhost:8080/#) in <module>
     17 sys.path.append('/usr/local/lib/python3.7/site-packages/')
     18 from biopandas.pdb import PandasPdb
---> 19 import simtk.openmm as mm
     20 import simtk.openmm.app as app
     21 from simtk.openmm import unit

2 frames
[/usr/local/lib/python3.7/site-packages/openmm/openmm.py](https://localhost:8080/#) in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _openmm
     14 else:
     15     import _openmm

ImportError: cannot import name '_openmm' from partially initialized module 'openmm' (most likely due to a circular import) (/usr/local/lib/python3.7/site-packages/openmm/__init__.py)

---------------------------------------------------------------------------

**Comment by pablo-arantes** [comment]
Hi @kva0987,

Thank you for your message. I will check the error. Google Colab have updated the python version to 3.8, I need to check if this update affected the notebook. 
I will let you know as soon as possible. 

Best,

Pablo

**Comment by pablo-arantes** [comment]
HI @kva0987,

I've fixed the error. Please, let me know if everything is working fine.

Thank you.

Pablo

**Comment by kva0987** [comment]
Hi,

It is working seamlessly.
Thank you!
