### ISSUE TITLE
new issues

### ISSUE THREAD

**Issue by zjl894150094** [pablo-arantes/making-it-rain#45]
Hi, 
 I get error messages as below just recently;
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-4-ca0af1623d5d>](https://localhost:8080/#) in <module>
----> 1 import pybel
      2 import rdkit
      3 import mdtraj as md
      4 from rdkit import Chem
      5 from rdkit.Chem import AllChem,Draw

ModuleNotFoundError: No module named 'pybel'

---------------------------------------------------------------------------

**Comment by pablo-arantes** [comment]
HI @zjl894150094,

Thank you for letting me know. I will check and let you know when it's done.

Best,

Pablo

**Comment by pablo-arantes** [comment]
HI @zjl894150094,

I've fixed the error. Please, let me know if everything is working fine.

Thank you.

Best,

Pablo

**Comment by zjl894150094** [comment]
Thank you sir.

**Comment by zjl894150094** [comment]
Hi,Sir
I got new error messages as below:

ValueError                                Traceback (most recent call last)
[<ipython-input-19-a442ca6c8d0e>](https://localhost:8080/#) in <module>
     34   ppdb.to_pdb(path="temp.pdb", records=['ATOM', 'HETATM'], gz=False, append_newline=True)
     35 
---> 36   mol= [m for m in pybel.readfile(filename="temp.pdb", format='pdb')][0]
     37   mol.calccharges
     38   mol.addh()

[/usr/local/lib/python3.8/site-packages/openbabel/pybel.py](https://localhost:8080/#) in readfile(format, filename, opt)
    157             obconversion.AddOption(k, obconversion.INOPTIONS, str(v))
    158     if not formatok:
--> 159         raise ValueError("%s is not a recognised Open Babel format" % format)
    160     if not os.path.isfile(filename):
    161         raise IOError("No such file: '%s'" % filename)

ValueError: pdb is not a recognised Open Babel format
