### ISSUE TITLE
Protein_ligand.ipynb pybel issue

### ISSUE THREAD

**Issue by kva0987** [pablo-arantes/making-it-rain#46]
Hi,

I was running Protein_ligand module.

While I was running to provide input files, there was an error message saying pybel that it cannot import pybel.

Also, when I tried to "Enumerate Stereoisomers to generate ligand topology", I see error message as below;

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-11-f324a4cc8a04>](https://localhost:8080/#) in <module>
      8 ##@markdown **You can find the smiles for your lingad at: https://pubchem.ncbi.nlm.nih.gov/**
      9 
---> 10 mol= [m for m in pybel.readfile(filename=ligand_pdb2, format='pdb')][0]
     11 mol.calccharges
     12 mol.addh()

AttributeError: module 'pybel' has no attribute 'readfile'

Could you look into this issue?

Best,

**Comment by kva0987** [comment]
My issue I think is similar to zjl894150094.

**Comment by kva0987** [comment]
I think the issue is that openbabel is not correctly installed, because I cannot import openbabel. It says no module for openbabel.

**Comment by kva0987** [comment]
The issue with pybel gets resolved when I do as below;

!conda install -c conda-forge openbabel  --yes
from openbabel import pybel
mol= [m for m in pybel.readfile(filename=ligand_pdb2, format='pdb')][0]

**Comment by pablo-arantes** [comment]
Hi @kva0987,

Thank you for letting me know about the issue. I will check and back to you. 

Best,

Pablo

**Comment by kva0987** [comment]
Hi,

Is it possible in Protein_ligand.ipynb, PDBFixer ligand without adding ligand hydrogens?

I am using a ligand with known protonation state, so that I want to keep the hydrogens.
But if I don't add hydrogens, chiralCentres are not defined when doing "Enumerate Stereoisomers to generate ligand topology:".

**Comment by Hamza1401** [comment]
Hi, 
I have already the same problem with pybel 

best,

**Comment by pablo-arantes** [comment]
HI @kva0987,

I've fixed the error. Please, try again and let me know if everything is working fine.

Thank you.

Best,

Pablo
