### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by KAO-KI** [pablo-arantes/making-it-rain#48]
ImportError: cannot import name '_openmm' from partially initialized module 'openmm' (most likely due to a circular import) (/usr/local/lib/python3.7/site-packages/openmm/__init__.py)
![1](https://user-images.githubusercontent.com/110063041/206016747-6fbd6289-14bc-417b-89a1-24231214573c.png)

**Comment by kva0987** [comment]
This was solved by changing python version to 3.8

**Comment by pablo-arantes** [comment]
Hi All,

I've already changed all the notebooks for the python version 3.8 (new version on Google Colab).

Thank you.

Best,

Pablo

**Comment by KAO-KI** [comment]
thank you sir.
