### ISSUE TITLE
Loading the necessary input files

### ISSUE THREAD

**Issue by KAO-KI** [pablo-arantes/making-it-rain#50]
ValueError: pdb is not a recognised Open Babel format
![2022-12-24 21 10 50](https://user-images.githubusercontent.com/110063041/209449874-6bda7be0-a4c2-49c7-8acf-fc4ded055ab6.png)

**Comment by tasyriqomar** [comment]
same with me.

**Comment by alinokhbe** [comment]
i have this exact same error

**Comment by pablo-arantes** [comment]
Hi All,

Thank you for letting me know about the issue. I've fixed the notebook.
Please, note that now we've updated all notebooks to [CondaColab](https://github.com/conda-incubator/condacolab). Now, all the dependencies will be installed faster than before. You will see a CondaColab cell, just run and wait a few seconds, the session will restart and it's normal.

Please, let me know if everything is working fine.

Thank you.

Best,

Pablo

**Comment by KAO-KI** [comment]
thank you, sir, verry mach.
best,
kao-ki

**Comment by alinokhbe** [comment]
Hello Pablo
Thank you for fixing the notebook. The import is working like a charm.
Best Regards
Ali Nokhbehzaim
