### ISSUE TITLE
Parameters to generate the topology:

### ISSUE THREAD

**Issue by KAO-KI** [pablo-arantes/making-it-rain#53]
![Screenshot at 2023-01-26 19-18-45](https://user-images.githubusercontent.com/110063041/214917981-07ad4012-4f3d-4a99-97ba-565309edeebc.png)

**Comment by pablo-arantes** [comment]
Hi @KAO-KI,

This is issue is on topology generation. The tleap is not able to create your topology for your protein/ligand structure. 
Can you please double-check your ligand PDB? Please, compare with examples PDB that we have here in GitHub (https://github.com/pablo-arantes/making-it-rain/tree/main/PROTEIN_LIGAND) for the protein ligand notebook.

I hope it helps.

Thank you.

Best,

Pablo

**Comment by KAO-KI** [comment]
Good morning sir,
Ok sir, I will check it.
Thank you very much.
Yours sincerely.
