### ISSUE TITLE
Interaction Energy

### ISSUE THREAD

**Issue by KAO-KI** [pablo-arantes/making-it-rain#54]
![2023-02-26 18 16 29](https://user-images.githubusercontent.com/110063041/221427377-ddac51f8-8542-4b89-9a73-f244e4ef0a08.png)

**Comment by KAO-KI** [comment]
hello sir,

is this plot normal?

thank you.

**Comment by pablo-arantes** [comment]
HI @KAO-KI,

No, this is not normal. Please, check your inputs. I've checked here and everything worked fine for me. 
Follow my plot:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/35934150/224112859-3ac56e6b-acd0-48da-8bd7-3fe8ba34f94d.png">

Another point, are you using GAFF or OpenFF parameters for the ligand?

Thank you.

Best,

Pablo
