### ISSUE TITLE
Topology

### ISSUE THREAD

**Issue by ggalueduran** [pablo-arantes/making-it-rain#55]
I have problems generating the top file
![image](https://user-images.githubusercontent.com/84942607/222470133-6aec4f44-65e8-42a8-adca-c4b5aa40e517.png)

How can I know what's exactly the error in my pdb file that makes tleap unable to generate the topology file? Is there a way to see the error log?

**Comment by zhenwilliam** [comment]
@ggalueduran , I met the same error today.

**Comment by pablo-arantes** [comment]
Hi All,

I've checked here and everything is working fine for me. Please, check your ligand input file. This is happening because the code is not able to create the topology for the ligand. When this is happening, probably is due ligand PDB file. Check our example file (https://github.com/pablo-arantes/making-it-rain/tree/main/PROTEIN_LIGAND) and compare with your ligand PDB file, please.

I hope it helps.

Thank you.

Best,

Pablo

**Comment by zhenwilliam** [comment]
Dear Professor @pablo-arantes , I have noticed that every time I upload a protein file with a lipid bilayer, it reports this error mentioned above. However, when I upload a protein file alone, there is no error. I am wondering how I can perform a simulation of a membrane protein-ligand complex. Can you please advise me on this matter?

**Comment by zhenwilliam** [comment]
The file I uploaded was” step5_assembly.pdb“created by membrane builder, CHARMM-GUI.

**Comment by mdpoleto** [comment]
@zhenwilliam I am confused. You mentioned that you are using CHARMM-GUI to create your coordinate and topology files, but you are reporting an error from an Amber notebook. Can you clarify with more details what are you attempting to do?

Let me also remind you that our notebooks ARE NOT suited for membrane simulations. For that you would need to modify the barostat (more information here: http://docs.openmm.org/development/api-python/generated/openmm.openmm.MonteCarloMembraneBarostat.html)

**Comment by zhenwilliam** [comment]
Dear Professor @mdpoleto, thank you for your advice. I have been attempting to perform simulations of membrane proteins, but as you noted, it seems that the membrane component cannot be detected by this notebook. I am grateful for your insight on this matter. I would also like to express my appreciation to you and your colleagues for your valuable contributions to the scientific community.
