### ISSUE TITLE
MM-PBSA method to calculate the binding free energy+Interaction Energy

### ISSUE THREAD

**Issue by farescre** [pablo-arantes/making-it-rain#56]
hello sir i'm getting some trouble:
All worked normally until MM-PBSA , i'm gettin this error code 
Traceback (most recent call last)
[<ipython-input-31-32db19b7b751>](https://localhost:8080/#) in <module>
     57     sys.stdout = original_stdout # Reset the standard output to its original value
     58 
---> 59 get_ipython().system('chmod 700 run_MMPBSA.sh 2>&1 1>/dev/null')
     60 get_ipython().system('bash run_MMPBSA.sh 2>&1 1>/dev/null')
     61 

2 frames
[/usr/local/lib/python3.8/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in _run_command(cmd, clear_streamed_output)
    161   locale_encoding = locale.getpreferredencoding()
    162   if locale_encoding != _ENCODING:
--> 163     raise NotImplementedError(
    164         'A UTF-8 locale is required. Got {}'.format(locale_encoding))
    165 

NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968

Then with interaction energy i'm getting an abnormal image and energy 
![Untitled](https://user-images.githubusercontent.com/121833676/222897335-ef56bf9f-2316-461e-bffc-3fa904d291bd.png)

**Comment by farescre** [comment]
please sir can you help me

**Comment by pablo-arantes** [comment]
Hi @farescre,

I've updated the code. Now it's working fine.

Thank you.

Best,

Pablo
