### ISSUE TITLE
Install dependencies: ModuleNotFoundError: No module named 'openmm'

### ISSUE THREAD

**Issue by rayx1** [pablo-arantes/making-it-rain#57]
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-21-dce26ec4d0bf>](https://localhost:8080/#) in <module>
      1 #load dependencies
----> 2 from openmm import app, unit
      3 from openmm.app import HBonds, NoCutoff, PDBFile
      4 from openff.toolkit.topology import Molecule, Topology
      5 from openff.toolkit.typing.engines.smirnoff import ForceField

ModuleNotFoundError: No module named 'openmm'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by zhenwilliam** [comment]
The same

**Comment by zhenwilliam** [comment]
Hello @rayx1 , I wanted to let you know that I found a solution to this issue. Instead of using “!mamba” in cell 2, you can try replacing it with "!conda". This should fix the bug you're experiencing.

**Comment by zhenwilliam** [comment]
Hi @rayx1 , I just found out after 7minutes running, this workaround failed.  Sorry for that.

**Comment by saguileran** [comment]
Pablo,

Thanks for the solution, it solves the problem!
 
Yours sincerely,

Sebastian

**Comment by rayx1** [comment]
Thanks @pablo-arantes for the update. Using the fallback runtime version temporarily allows access to the last version of the runtime before the upgrade described above, and is available until mid-March. [https://github.com/googlecolab/colabtools/issues/3450](url)

**Comment by pablo-arantes** [comment]
I've fixed the code, now CondaColab is working fine with python 3.9. Thank you.

**Comment by rayx1** [comment]
Thanks @pablo-arantes
