### ISSUE TITLE
An issue report in MM-PBSA method to calculate the binding free energy

### ISSUE THREAD

**Issue by zhenwilliam** [pablo-arantes/making-it-rain#58]
Hello, sir. I just met an issue in MM-PBSA method to calculate the binding free energy.

NameError                                 Traceback (most recent call last)
[<ipython-input-3-c0873da11184>](https://localhost:8080/#) in <module>
     26 Output_name = 'FINAL_RESULTS_MMPBSA' #@param {type:"string"}
     27 
---> 28 final_mmpbsa = os.path.join(workDir, Output_name)
     29 
     30 if number_frames_analysis > 10:

NameError: name 'os' is not defined

**Comment by mdpoleto** [comment]
@zhenwilliam this is, by far, not enough information to understand what you are doing or if this is a notebook error or a user error. Please provide more details of what you are attempting to do.

**Comment by pablo-arantes** [comment]
I've fixed the code. Thank you.
