### ISSUE TITLE
Interaction energy

### ISSUE THREAD

**Issue by farescre** [pablo-arantes/making-it-rain#59]
Dear sir, I am running a md simulation and getting some trouble with interaction energy: for 10ns all is okay, but for 100 ns I have an anomaly below you will find the images
![image](https://user-images.githubusercontent.com/121833676/224579419-6620ac9c-6528-472c-b674-dc66c4beca02.png)
![image](https://user-images.githubusercontent.com/121833676/224580087-5c25dc59-f701-4250-9ed5-fc3385643fb9.png)
I used the same input files for both the simulations, please can you help

**Comment by mdpoleto** [comment]
@farescre with the amount of information provided, I can't judge if this is an actual error or not. What I can say is that a spike like that in VdW interaction energies suggest some atoms are getting closer than they should. I can't say anything else without more information.

**Comment by farescre** [comment]
@mdpoleto, hello sir thank you for the answer, what informations can i provide to you

**Comment by nyubachi** [comment]
Thank you for providing us with a great product.
By the way, I have the same problem.
I have calculated with Protein_ligand.ipynb using PDB 3KQ0 and data from PubChem CID 445639.
![Interaction_energy](https://user-images.githubusercontent.com/96689/232188191-193b1a78-2b21-4f20-a1ae-ef33db8da311.png)
