### ISSUE TITLE
Error during parametrization

### ISSUE THREAD

**Issue by 1heman** [pablo-arantes/making-it-rain#6]
Hi. The error that I'm reporting here has been seen with many protein-ligand pairs.

In the parametrization step (in the Protein_ligand.ipynb notebook), the following error was seen.

```
NameError                                 Traceback (most recent call last)
<ipython-input-6-b8ef11d5d9db> in <module>()
    158         vol = float(line.split()[1])
    159 
--> 160 vol_lit  = vol * pow(10, -27)
    161 atom_lit = 9.03 * pow(10, 22)
    162 conc = float(Concentration)

NameError: name 'vol' is not defined
```
The line in line #158 is being read from a temporary copy of a part of leap.log file that contains 'Volume:'. However, this word 'Volume:' is not present in leap.log file.

This error was also seen in the issue #5 

Attached with this is one of the pdb files which gave this error. ([5ES1.txt](https://github.com/pablo-arantes/making-it-rain/files/7490071/5ES1.txt))
I have used the ligand from this pdb file and made a complex with another protein. 

Any help would be deeply appreciated.
Thank you
- Hemant

**Comment by pablo-arantes** [comment]
Hi @1heman 

Thank you for your message.
Regarding your error, I tested your pdb file. I have created ligand.pdb and protein.pdb (attached) from your 5ES1.txt file. Everything worked fine for me, I ran all the steps and I didn't have any errors. My suggestion is to check your input files (protein.pdb and ligand.pdb). Not only that, remember to run all the cells in correct order. If your ligand does not have hydrogens, you should select the option **yes** in the first cell. 
Follow the prints for your system: 
![image](https://user-images.githubusercontent.com/35934150/140622368-cc2739bc-6c3a-4e0b-af23-0ec5bd428929.png)
![image](https://user-images.githubusercontent.com/35934150/140622340-7cca74df-fdeb-4312-b37e-39b1410d4a1b.png)
![image](https://user-images.githubusercontent.com/35934150/140622345-2c9bd252-ab8c-40f5-8c7e-0dc78a125512.png)
![image](https://user-images.githubusercontent.com/35934150/140622348-c8ae5e67-099b-4a02-801b-cb89354e0199.png)
![image](https://user-images.githubusercontent.com/35934150/140622352-1009ffaa-348e-48f5-b186-03f3e50603b3.png)

Let me know if you have any questions.

Thank you. 

Best,

Pablo

[ligand.txt](https://github.com/pablo-arantes/making-it-rain/files/7491155/ligand.txt)
[protein.txt](https://github.com/pablo-arantes/making-it-rain/files/7491156/protein.txt)

**Comment by 1heman** [comment]
Hi @pablo-arantes 

The pdb that I've sent you isn't exactly the one that gave me the error. I had aligned my subject protein with **5es1**. Then used my subject protein in the MD simulation. So, it looks like the error lies with my subject protein. In fact, in all the cases where I had come across the error, the subject protein was common. I think that's where the problem is.

I will close this for now. In case I still come across some errors, I'll request your time.

Thank you @pablo-arantes 

Hemant
