### ISSUE TITLE
Ligand protein interaction can't run

### ISSUE THREAD

**Issue by Fahryshitpost** [pablo-arantes/making-it-rain#62]
Hi dear, I ran into problem that I can't run the code on "parameter to generate the topology" part because the ligand_gaff.pdb couldn't be produced, how to fix this issue? thank u in advanced and have a blessed day
![Screen Shot 2023-04-11 at 16 17 53](https://user-images.githubusercontent.com/130448056/231114949-91d1c63e-c3a7-449c-9cdd-95b3a47c99fb.png)
![Screen Shot 2023-04-11 at 16 18 07](https://user-images.githubusercontent.com/130448056/231114962-da27fdd3-13c9-4f7d-9b70-a2b1a96c4fbd.png)

**Comment by pablo-arantes** [comment]
BTW If you want to run with two ligands simultaneously, you can check the following notebook:
https://colab.research.google.com/github/pablo-arantes/making-it-rain/blob/main/Protein_2ligands.ipynb

Thank you.
