### ISSUE TITLE
GPU Acceleration

### ISSUE THREAD

**Issue by Sundharesan10** [pablo-arantes/making-it-rain#63]
Hi sir, You work is very great sir and thanks a lot for this sir. While I'm running the notebook i came across the gpu usage and it is showing only 0.3 usage out of 15gb ram. I checked while running all the process but the usage is same only.

**Comment by pablo-arantes** [comment]
I'm not able to understand your question, the code is using gpu provide by Google. If you run one of the first cells, you can check if you allocated the gpus or not. When you run the equilibration or production cell, OpenMM engine will use gpu to perform the MD simulations. For our calculations we don't need too much ram memory, that is the reason you are seeing only 0.3 of usage.
