### ISSUE TITLE
Issue with histidine residues

### ISSUE THREAD

**Issue by harrynov22** [pablo-arantes/making-it-rain#65]
Hi, my histidine residues in my protein (HID: Histidine with hydrogen on the delta nitrogen), always get removed in the topology in Amber.ipynb. Is there a way I can fix this problem?

**Comment by pablo-arantes** [comment]
Hi @harrynov22,

Sorry for my delay.
Thank you for letting me know about the issue. 
I will check the code and let you know.

Thank you.

**Comment by pablo-arantes** [comment]
Hi @harrynov22,

I've fixed the code. Now should work fine, not only that now Amber notebook works for protein, nucleic acids and glycans. 

Please, let me know if everything is working fine.

Thank you.

Best,

Pablo
