### ISSUE TITLE
Is it possible to simulate one protein and two ligands simultaneously?

### ISSUE THREAD

**Issue by nyubachi** [pablo-arantes/making-it-rain#66]
Thank you for the wonderful structure you have created.
I enjoy using "Protein_ligand.ipynb".

I am a beginner in MD simulation, so this may be a silly attempt,
I would like to modify "Protein_ligand.ipynb" to simulate a protein and two ligands simultaneously.

Since it is difficult for me to determine if such an attempt is even possible,
I would appreciate your comments and advice.

Thanks in advance.

**Comment by nyubachi** [comment]
Thank you for your response.

I am also trying, but due to my lack of knowledge of MD simulation and my low proficiency in Python, 
I am having difficulties around the "Parameters to generate the protein topology:" cell.

Any hints or overview of the fixes would be appreciated.
Thanks in advance for your help.

**Comment by pablo-arantes** [comment]
Hi @nyubachi,

Follow the notebook to run a protein complexed two ligands simultaneously.
https://colab.research.google.com/github/pablo-arantes/making-it-rain/blob/main/Protein_2ligands.ipynb

I hope it helps.

Thank you.

**Comment by nyubachi** [comment]
I really appreciate you taking the time out of your busy schedule to create the code.

I am currently running a test simulation based on the code you provided, 
and it seems to be working well.

I will definitely use it effectively and contribute to the development of my research field and the health of patients.

Thank you very much.
