### ISSUE TITLE
install dependencies can't work

### ISSUE THREAD

**Issue by puguh173224** [pablo-arantes/making-it-rain#68]
Hi sir, Your "make it rain" is great. The last time I tried amber and protein-ligand simulation is successful. but after that, I try again and encounter an error in the install dependencies. how to fix this problem?
Thank You
![Screenshot 2023-04-28 201944](https://user-images.githubusercontent.com/132072917/235161285-c0da278a-922a-42d2-88b1-083f23accf63.png)

**Comment by pablo-arantes** [comment]
Hi @puguh173224,

Google Colab updated to python 3.10. Now, it's having problem with OpenMM. I'm trying to fix, I will let you know when it's done.

Thank you.

**Comment by pablo-arantes** [comment]
Hi @puguh173224,

Everything is working fine now. 

Thank you.

Best,

Pablo

**Comment by harrynov22** [comment]
I have the same problem

**Comment by pablo-arantes** [comment]
Can you please provide more information regarding the issue? And I'm a little bit confuse here, which notebook are you using? The Amber notebook or the Protein-ligand notebook?

**Comment by puguh173224** [comment]
I use amber notebook 
![Screenshot 2023-05-04 222441](https://user-images.githubusercontent.com/132072917/236711796-31d1f233-f933-4991-9b78-c21092df25bb.png)
![Screenshot 2023-05-04 222602](https://user-images.githubusercontent.com/132072917/236711801-a937d2dd-c67d-46ae-b1af-5dcdd1f5ea55.png)

**Comment by pablo-arantes** [comment]
Ok! Thank you for the information. 
This error is because tleap is not able to create your topology. Are you using your own PDB file? If yes, I suggest checking your input PDB file. Remember, the Amber notebook works only for protein, nucleic acids and glycans systems, if you have different molecule tleap will not be able to create your topology.
I've tested here for the PDB ID 1AKI and everything went fine.

**Comment by puguh173224** [comment]
Yes, it was also OK when I tested for PDB ID 1 AKI. But when I use my own system PDB protein with code 5OQV, it can not create the topology. last month, before the system updated, everything worked OK. 
thank you.

**Comment by pablo-arantes** [comment]
Hi,

Thank you for letting me know. I've fixed the code, I've tried with your PDB ID (5OQV) and everything worked fine. 
Please, open the notebook again and try. 

Best,

Pablo
