### ISSUE TITLE
Is it possible to run a binding energy decomposation(per residue) for a protein(peptide)-protein(receptor) system, using amber here on Colab?

### ISSUE THREAD

**Issue by Infinite-Rainfall** [pablo-arantes/making-it-rain#69]
For peptide designers, it is common to use AF2 to co-predict the structure of a peptide binder along with the protein receptor. I noted that a notebook is provided here for binding free energy calculation using MMPBSA method after amber MD simulation. Will it possible to modify that notebook to calculate the binding free energy and decompose it to residues in order to evaluate the contribution of different amino acids in the peptide binder?

Or at least, I wonder how should I modify the note book for "Protein_ligand" to achieve this function?

**Comment by pablo-arantes** [comment]
Hi @Infinite-Rainfall,

Sorry for my delay. 
Regarding your question, yes, you can modify the code to calculate binding free energy and decompose it to residues.  I strongly suggest you take a look at  [MM-PBSA page](https://ambermd.org/tutorials/advanced/tutorial3/py_script/section6.php) on Amber tutorials. 
Another possibility is to change the code using Pytraj and MDAnalysis libraries in python. You can create a function where you perform a loop in each residue you want to calculate the energy.

I hope it helps.

Thank you.

Pablo
