### ISSUE TITLE
Error on module prolif during protein-ligand md

### ISSUE THREAD

**Issue by anchy2111** [pablo-arantes/making-it-rain#73]
Hi, this error pops up every time even if all the dependencies are installed. I can't see de trajectory with LigPlot. I tried to manually install prolif but the error persist during protein-ligand simulation.

ModuleNotFoundError                       Traceback (most recent call last)

[<ipython-input-8-31ccc739a579>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 import MDAnalysis as mda
----> 5 import prolif as plf
      6 import numpy as np
      7 import os

ModuleNotFoundError: No module named 'prolif'

**Comment by pablo-arantes** [comment]
Hi @anchy2111,

I've fixed the code, I tried and everything worked fine.
Please, open the notebook again and try.

Best,

Pablo
