### ISSUE TITLE
Equilibration output error

### ISSUE THREAD

**Issue by jdernic** [pablo-arantes/making-it-rain#75]
Dear Dr. Arantes,

First of all thank you for creating these notebooks.

I am writing in regards of the CHARMM-GUI input notebook. I am having issues with the equilibration step of a cyan fluorescent protein. I have created the input using CHARMM-GUI solution builder, which includes a modified amino acid (the chromophore). When I run the equilibration step it seems to immediately kick the protein out of the solvation box. Is this due to the modified amino acid? Would you have any recommendations on how to fix this problem?

I ran the example (1aki) simulation and it worked just fine.

I look forward to your response.

Kind Regards,

Jan

**Comment by mdpoleto** [comment]
Hi @jdernic . Assuming your equilibration is not crashing and you have a normal trajectory, what you described sounds like a simple PBC issue, where you are seeing the virtual image of your protein. Can you give us more details of which step you are running successfully and what is causing you issues?

I am assuming that you are visualizing the equilibration somehow and your ligand is within the water box while the protein is jumping but I want to confirm before suggesting any action.

**Comment by jdernic** [comment]
Dear Dr. Poleto,

Thank you for your quick response. 
Yes it is as you suggest. Initially when I visualize the input pdb file the protein is properly located inside the box. Also the equilibration step runs successfully, however when I visualize the output .pdb file and its trajectory in PyMol the protein seems to be on the edge of the box since the first equilibration step and then jumps around. 
However, the chromophore is not added as a ligand, rather as a modified amino acid (covalently bound to the protein).

**Comment by jdernic** [comment]
This is what the output looks like
<img width="739" alt="Screenshot 2023-07-24 at 18 55 43" src="https://github.com/pablo-arantes/making-it-rain/assets/140412449/c9420dd8-1747-441e-8437-aa9aa51877c9">

**Comment by mdpoleto** [comment]
Hi @jdernic yes, this is a well known PBC bug, but not an issue. The final .pdb written by OpenMM sometimes does not have your desired solute centered in the box. Your simulation is still completely valid. Thus, it is not a problem arising from our notebooks.

You can recenter your protein inside the simulation box by using several algorithms nowadays. MDAnalysis does a pretty good job at it (and our notebooks have a visualization cell where you can find a MDAnalysis code snippet so you can just use that), but you can also use other packages such as CHARMM or AMBER (depending which type of inputs you are using).

**Comment by jdernic** [comment]
Thank you very much for the help. I will recenter with MDAnalysis then.

**Comment by mdpoleto** [comment]
Perfect. Since it seems the bug/issue is solved, I am closing it.
