### ISSUE TITLE
Error in 'Parameters to generate the topology'

### ISSUE THREAD

**Issue by jcatiggay** [pablo-arantes/making-it-rain#76]
I'm trying to run a MD simulation with BuChE protein with fluorenyl ligand. Upon running the code under Parameters to generate the topology:, I get an error on line 159 NameError: name 'vol' is not defined. 

![image](https://github.com/pablo-arantes/making-it-rain/assets/68776210/eb445b87-d69c-4a18-a9af-f2e15824f8e4)

**Comment by pablo-arantes** [comment]
HI @jcatiggay,

Seems to me, you have an issue in the PDB file of your ligand. Can you please double-check your input files? I suggest comparing with our input example files (https://github.com/pablo-arantes/making-it-rain/tree/main/PROTEIN_LIGAND).

If the error persists, maybe the protonation could be the problem. Our notebook uses RDkit to add the hydrogens in the small molecules. It works well for aliphatic chains or aromatic rings, but when you submit a more complex molecule as a ligand, you can have issue in the **Add_ligand_hydrogens** step. If you have a complex molecule as a ligand, my suggestions are to submit the molecule already with the hydrogens in the right protonation state and then select **no** on **Add_ligand_hydrogens** option in the first cell.

I hope it helps.

Thank you.

Best,

Pablo
