### ISSUE TITLE
Protein-Nucleic Acid Complex Simulation.

### ISSUE THREAD

**Issue by SsemuyigaMHC** [pablo-arantes/making-it-rain#77]
Dear Authors, Which model can I use for Protein-Nucleic Complex simulations.
Thank you.

**Comment by pablo-arantes** [comment]
HI @SsemuyigaMHC,

You can use the AMBER notebook (https://colab.research.google.com/github/pablo-arantes/Making-it-rain/blob/main/Amber.ipynb). In theory, it should work well for protein-nucleic acids complex. 

Please, let me know if you have any issues.

Thank you.

**Comment by SsemuyigaMHC** [comment]
Thank you very much @pablo-arantes 
I will let you know in case of any issues.
