### ISSUE TITLE
There is no option to run MMGBSA in this code repo. Please fix it

### ISSUE THREAD

**Issue by mainguyenanhvu** [pablo-arantes/making-it-rain#79]
I found that there is no option to run MMGBSA in [this code](https://github.com/pablo-arantes/making-it-rain/blob/main/Protein_ligand.ipynb). 

Please help me to fix it. Thank you very much.

**Comment by pablo-arantes** [comment]
Hi @mainguyenanhvu,

I'm not able to understand your issue. There is a cell to run MMGBSA in the notebook (follow the picture). What is your issue? 

<img width="1711" alt="image" src="https://github.com/pablo-arantes/making-it-rain/assets/35934150/8ead763b-f81d-437d-bcfb-6aec6b477df7">

Thank you.

Best,

Pablo

**Comment by mainguyenanhvu** [comment]
Hi @pablo-arantes, I think that MMGBSA and MMPBSA are different. Thus, I would like to run only MMGBSA. How could I set up parameter for doing this. 

Besides, If I just want to run MMGBSA without previous step (MD simulation), which file do I need to repair? 

Thank you very much.

**Comment by pablo-arantes** [comment]
Of course, they are different. But if you check the description in the cell, we are calculating both (MMGBSA and MMPBSA). 
If you want to run only MMGBSA and use your own files, you should take a look in the AMBER tutorials: https://ambermd.org/tutorials/advanced/tutorial3/

I hope it helps.

Thank you.

**Comment by mainguyenanhvu** [comment]
Hi @pablo-arantes, I would like to ask you one more question about which module do I need to import when using complex_structure.createSystem? 

Thank you very much.

**Comment by pharm-dacnhan** [comment]
Hi @pablo-arantes , actually I could not find the code line in your script that show the combination of mmgbsa and mmpbsa. In addtion, I would like to know more detail about the comparison procedure, whether the final energy value would be calculated by combining two methods?

**Comment by pablo-arantes** [comment]
> Hi @pablo-arantes , actually I could not find the code line in your script that show the combination of mmgbsa and mmpbsa. In addtion, I would like to know more detail about the comparison procedure, whether the final energy value would be calculated by combining two methods?

Hi @pharm-dacnhan,

The script is calculating both methods and giving the results of the both separately. If you check the output you can see that.  

In the following code, we are creating the input file to run MMPBSA and MMGBSA calculations using AmberTools. I commented the lines for each method. 

f = open("mmpbsa.in", "w")
f.write("""&general """  + "\n"
"""  endframe=""" + str(int(number_frames_analysis)) + """,  interval=""" + str(int(stride)) + """, strip_mask=:WAT:Na+:Cl-:Mg+:K+, """ + "\n"
"""/ """ + "\n"
**#MMGBSA calculation**
"""&gb """ + "\n"
""" igb=""" + str(igb) +  """, saltcon=""" + str(Salt_concentration) +  """, """ + "\n"
"""/ """ + "\n"
**#MMPBSA CALCULATION**
"""&pb """ + "\n"
""" istrng=""" + str(Salt_concentration) +  """, inp=2, radiopt=0, prbrad=1.4, """ + "\n"
"""/""")
f.close()
