### ISSUE TITLE
OS error

### ISSUE THREAD

**Issue by ShrikirtiAnand** [pablo-arantes/making-it-rain#82]
I am running a 100ns MD for protein-protein complex (118 aa and 121 aa = 239 aa) in the notebook by taking a Colab pro version. I got an 'OS error: Transport endpoint not connected' after 4 hrs of run. I have put the stride time as 10ns and number of strides as 10. How do I fix it?
I have attached a picture for reference.
![WhatsApp Image 2023-10-06 at 09 28 45](https://github.com/pablo-arantes/making-it-rain/assets/133743001/7e76df6c-ef8b-46c8-a4d1-902704746d40)

**Comment by pablo-arantes** [comment]
HI @ShrikirtiAnand,

Sorry for my delay.
I looked into your issue and seems to me this a problem on Google Drive, you can check here: https://github.com/googlecolab/colabtools/issues/3441

My suggestion for you is to perform more strides with less nanoseconds. For example, instead to use 100 of 10ns, you can try 50 strides of 2ns. With that, if the connection is gone you would have save the most part of your MD simulation.

I hope it helps.

Thank you.

Best,

Pablo

**Comment by ShrikirtiAnand** [comment]
Thank you for the response, Sir. I will try 50 strides of 2 ns. Thank you.
