### ISSUE TITLE
It doesn't show the RMSD graphic with the protein-ligand

### ISSUE THREAD

**Issue by Eliel83** [pablo-arantes/making-it-rain#83]
Hello
Sorry, I can't generate the RMSD plot with the protein and ligand.
Could you help me? I share an example 

https://github.com/pablo-arantes/making-it-rain/assets/148513105/c81ba69b-80d7-4a17-a5c2-693826401143

**Comment by pablo-arantes** [comment]
Hi @Eliel83,

Sorry for my delay. You can try to use pytraj to perform RMSD of the ligand and plot with the protein RMSD with matplotlib. 
You can use the same cell we are using in Making it Rain. Just need to include the ligand RMSD calculation and plot.
Here, you can find more information regarding how to calculate the RMSD with pytraj: https://amber-md.github.io/pytraj/latest/analysis.html#pytraj.rmsd

I hope it helps.

Best,

Pablo

**Comment by Eliel83** [comment]
Good night

Thank you, I ran the complex but it doesn't show the graphic

Thank you in advance
