### ISSUE TITLE
protein_ligand Colab - Violation occurred on line 240 in file Code/Numerics/Optimizer/BFGSOpt.h

### ISSUE THREAD

**Issue by dimkorov** [pablo-arantes/making-it-rain#84]
Hello,

I would like to run some protein-ligand simulations with your notebook but always get the error below when I am using any other ligand other than the example (the ligand from pdb: 3HTB):

It stops here
---> 84   ff.Minimize(maxIts=1000)

and the error is
****
Invariant Violation
bad direction in linearSearch
Violation occurred on line 240 in file /home/conda/feedstock_root/build_artifacts/rdkit_1692275722171/work/Code/Numerics/Optimizer/BFGSOpt.h
Failed Expression: status >= 0
****

Is there anything I can do to overcome this issue? Any help would be greatly appreciated.

Thank you in advance.

Best regards,
Dimitris

**Comment by dimkorov** [comment]
Just an additional info: it seems to me that adding the constrains is not the only issue (I could well be wrong of course). When I  modify the pdb file, then I got the error below:
RuntimeError                              Traceback (most recent call last)
[<ipython-input-8-c49df2e67024>](https://localhost:8080/#) in <cell line: 71>()
     82     if (a.GetAtomicNum() > 1):
     83       ff.MMFFAddPositionConstraint(a.GetIdx(), 0, 1.e4)
---> 84   ff.Minimize(maxIts=1000)
     85   charge_mol = Chem.rdPartialCharges.ComputeGasteigerCharges(hmol)
     86   charge = Chem.GetFormalCharge(hmol)

So, could you please suggest any workflow I could use to generate the correct ligand file (for files obtained after docking)?

Thanks again.

Best,
Dimitris

**Comment by pablo-arantes** [comment]
Hi @dimkorov 

Thank you for letting me know about the issue. I will take a look and back to you.

Thank you.

Best,

Pablo

**Comment by Elsword016** [comment]
I ran into a similar issue, it kind of got fixed when I used the 3D structure of the ligand from PubChem and used the .sdf file rather than converting it into a PDB (cause it triggered another error while generating topology, ligand_gaff.pdb wasn't getting created). Maybe this might solve your issue too.

**Comment by pablo-arantes** [comment]
Hello everyone,

I have changed the code. Please try running it again and inform me if it functions correctly.

Thank you.

Best regards
