### ISSUE TITLE
NAMD

### ISSUE THREAD

**Issue by Eliel83** [pablo-arantes/making-it-rain#85]
Hello... is it posible create a COLAB for NAMD?
It will be very useful

**Comment by pablo-arantes** [comment]
Hi @Eliel83,

As we said in the paper, the idea of Making it Rain is "**highlight the usage of a cloud-computing**".  Our notebooks are using OpenMM engine to run the molecular dynamics simulations. 
One suggestion is installing NAMD on Google Colab and run your simulations there.
Follow a notebook where they have shown how to install and run NAMD on Colab:
https://colab.research.google.com/drive/1KEd7TR37UUaculowjNe02ja_JlWlw0Jd?usp=sharing

I hope it helps.

Thank you.

Best,

Pablo
