### ISSUE TITLE
GROMACS with ligand

### ISSUE THREAD

**Issue by Eliel83** [pablo-arantes/making-it-rain#86]
is posible fix the COLAB to run molecular dynamics Protein-ligand in GROMACS?

**Comment by pablo-arantes** [comment]
Hi @Eliel83,

As we said in the paper, the idea of Making it Rain is "**highlight the usage of a cloud-computing**".  Our notebooks are using OpenMM engine to run the molecular dynamics simulations. 
One suggestion is installing Gromacs on Google Colab and run your simulations there.
Follow a video where they have shown how to install and run Gromacs on Colab: https://www.youtube.com/watch?v=HDlO13gvgsY&ab_channel=SelfStudy

I hope it helps.

Thank you.

Best,

Pablo
