### ISSUE TITLE
Prof. Dr. Salahalmula

### ISSUE THREAD

**Issue by Salahalmulla** [pablo-arantes/making-it-rain#89]
When I runs an Equilibration MD simulation (NPT ensemble)
The following problem appeared to me
TypeError: Unit "kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".
Best regards

**Comment by Salahalmulla** [comment]
How Can I solve the problem

**Comment by pablo-arantes** [comment]
Can you please tell me in which notebook you are having the issue? This error should not happen because I've fixed all the notebooks.

**Comment by Salahalmulla** [comment]
Thank you very much for fast response
The notebook is a Jupyter notebook for running Molecular Dynamics (MD) simulations using OpenMM engine and AMBER force field for Protein and Ligand systems
Best regards

**Comment by pablo-arantes** [comment]
Hi @Salahalmulla,

I just tried here, and the notebook works well. Can you please reopen the notebook from the Making it Rain repo? 
Maybe you are using an old version.

Thank you.

Best,

**Comment by Salahalmulla** [comment]
Ok
Best regards
