### ISSUE TITLE
GROMACS Protein topology defined in another .itp file

### ISSUE THREAD

**Issue by btam125** [pablo-arantes/making-it-rain#9]
This error: 

/usr/local/lib/python3.7/site-packages/pytraj/io.py in load_topology(filename, option)
    525     if top.n_atoms == 0:
    526         raise RuntimeError(
--> 527             'n_atoms = 0: make sure to load correct Topology filename '
    528             'or load supported topology (pdb, amber parm, psf, ...)')
    529     return top

However in the topol.top file, I have put:

#include "topol_Protein.itp"
#include "topol_Ion2.itp"

The protein topology was defined in the "topol_protein.itp". The error will disappear if I put the topol_Protein.itp information into the topol.top.

Thus, if the software can read both lines above and get the information. That would be great.

**Comment by pablo-arantes** [comment]
HI @btam125,

I have made some changes in the code, please, test and let me know if everything is working well now.

Thank you.

Best,

Pablo

**Comment by btam125** [comment]
Hi Pablo,

Thanks, it is working now.

Best,

Ben
