### ISSUE TITLE
Install dependencies fault (can't work)

### ISSUE THREAD

**Issue by ysa123-2** [pablo-arantes/making-it-rain#90]
Hi sir, Your "make it rain" is great. 
![fig](https://github.com/pablo-arantes/making-it-rain/assets/153471649/94bb3c7c-d9f2-4971-bc1a-5240267c7432)
The last time I tried amber and protein-ligand simulation is successful. but after that, I try again and encounter an error in the install dependencies. how to fix this problem?
Thank You

**Comment by Salahalmulla** [comment]
Hi sir
I am facing the same problem now
Best regards

**Comment by kadhirmn** [comment]
Hello sir,
I'm also facing the same problem sir. Please let us know how to rectify it.

Thank you.

**Comment by pablo-arantes** [comment]
Hi All,

I've fixed the code. Everything should work fine now.

Thank you for letting me know about the issue.

Best,

Pablo
