### ISSUE TITLE
Prof. Dr. Salahalmulla

### ISSUE THREAD

**Issue by Salahalmulla** [pablo-arantes/making-it-rain#91]
Hi pablo-arantes
After the fixation of install dependencies error by you yesterday, run is working, but when I reach 60-ns, The operation stopped and the following error appears:
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-6-3cda0212944a>](https://localhost:8080/#) in <cell line: 4>()
      2 #
      3 ###########################################
----> 4 import openmm as mm
      5 from openmm import *
      6 from openmm.app import *

ModuleNotFoundError: No module named 'openmm'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by pablo-arantes** [comment]
It seems that your session was terminated, so you'll need to reinstall the dependencies again.
