### ISSUE TITLE
Provide the necessary input files (cannot work)

### ISSUE THREAD

**Issue by Salahalmulla** [pablo-arantes/making-it-rain#92]
Hi sir 
Provide the necessary input files (cannot work) and the followings are appeared:

  [08:37:22] Explicit valence for atom # 1 O, 3, is greater than permitted
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
[<ipython-input-4-0e391ddeb36c>](https://localhost:8080/) in <cell line: 122>()
    187   out.close()
    188   hmol = Chem.MolFromMolFile('temp.mol', removeHs=False)
--> 189   charge_mol = Chem.rdPartialCharges.ComputeGasteigerCharges(hmol)
    190   charge = Chem.GetFormalCharge(hmol)
    191   print("Charge = " + str(charge))

ArgumentError: Python argument types in
    rdkit.Chem.rdPartialCharges.ComputeGasteigerCharges(NoneType)
did not match C++ signature:
    ComputeGasteigerCharges(RDKit::ROMol mol, int nIter=12, bool throwOnParamFailure=False)
Best regards

**Comment by pablo-arantes** [comment]
Hello,

It appears there is a problem during the 'preparation of the PDB file for the ligand' step. RDkit seems unable to properly interpret your ligand's structure. Could you take a moment to review your ligand PDB file for accuracy? For reference, you might find it helpful to compare your file with the example PDBs provided in our [GitHub repository](https://github.com/pablo-arantes/making-it-rain/tree/main/PROTEIN_LIGAND), specifically for the protein-ligand notebook.

Best regards,
Pablo

**Comment by Salahalmulla** [comment]
Thank you pablo
Best regards

**Comment by Salahalmulla** [comment]
Hi pablo
Since the error that occurred in the Independence install, and the problem
in:
["kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)"
Since then I haven't been able to run:
Provide the necessary input files
Note that the same files were working perfectly before these problems, and
I ran them at different times, different nanoseconds
It seems that there was confusion in this section after the above two
problems were fixed
The attached files for protein and ligand were used
Regards

‫في الجمعة، 15 ديسمبر 2023 في 10:06 م تمت كتابة ما يلي بواسطة ‪Pablo
Ricardo Arantes‬‏ ***@***.***‬‏>:‬
