### ISSUE TITLE
Error in provide the necessary input files

### ISSUE THREAD

**Issue by Salahalmulla** [pablo-arantes/making-it-rain#95]
Hi pablo
Since the error that occurred in the Independence install, and the problem in:
["kilojoule/mole" is not compatible with Unit "kilojoule/(nanometer*mole)"
Since then I haven't been able to run:
Provide the necessary input files
Note that the files were working perfectly before these problems, and I ran them at different times, different nanoseconds
It seems that there was confusion in this section after the above two problems were fixed
Regards

**Comment by pablo-arantes** [comment]
Hi @Salahalmulla,

Can you please let me know which notebook are you using? I just tried AMBER and protein_ligand notebooks and both are working properly.

Thank you.
