### ISSUE TITLE
protein_ligand.ipynb

### ISSUE THREAD

**Issue by kadhirmn** [pablo-arantes/making-it-rain#97]
Hello sir, I have been encountered with the following error. Kindly help me in this situation.

[06:51:58] Explicit valence for atom # 1 O, 3, is greater than permitted
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
[<ipython-input-6-ad699b3e6207>](https://localhost:8080/#) in <cell line: 122>()
    187   out.close()
    188   hmol = Chem.MolFromMolFile('temp.mol', removeHs=False)
--> 189   charge_mol = Chem.rdPartialCharges.ComputeGasteigerCharges(hmol)
    190   charge = Chem.GetFormalCharge(hmol)
    191   print("Charge = " + str(charge))

ArgumentError: Python argument types in
    rdkit.Chem.rdPartialCharges.ComputeGasteigerCharges(NoneType)
did not match C++ signature:
    ComputeGasteigerCharges(RDKit::ROMol mol, int nIter=12, bool throwOnParamFailure=False)

**Comment by Salahalmulla** [comment]
Hello all
I faced the same problem
[05:39:16] Explicit valence for atom # 1 O, 3, is greater than permitted
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
[<ipython-input-4-c3d9453f50b9>](https://localhost:8080/#) in <cell line: 122>()
    187   out.close()
    188   hmol = Chem.MolFromMolFile('temp.mol', removeHs=False)
--> 189   charge_mol = Chem.rdPartialCharges.ComputeGasteigerCharges(hmol)
    190   charge = Chem.GetFormalCharge(hmol)
    191   print("Charge = " + str(charge))

ArgumentError: Python argument types in
    rdkit.Chem.rdPartialCharges.ComputeGasteigerCharges(NoneType)
did not match C++ signature:
    ComputeGasteigerCharges(RDKit::ROMol mol, int nIter=12, bool throwOnParamFailure=False)

**Comment by pablo-arantes** [comment]
Hi All,

Sorry for the delay.
You have issues on your ligand PDB file, RDkit library is not able to read and compute the charges of your molecule. Can you please double-check your input file? 

Thank you.

**Comment by pablo-arantes** [comment]
Hi,

Sorry for the delay. The previous code was not able to compute the charges correctly. Now, I've changed the notebook, and you can assign the charge of your molecule. 

Please let me know if it's working fine.

Thank you.

Best,

Pablo
