### ISSUE TITLE
Glycam.ipynb Error generating Amber Topology

### ISSUE THREAD

**Issue by pramsland** [pablo-arantes/making-it-rain#98]
I get the following error when trying to generate the Amber Topology using the default parameters on Glycam.ipynb

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-11-0472264bf549>](https://localhost:8080/#) in <cell line: 77>()
     75         vol = float(line.split()[1])
     76 
---> 77 vol_lit  = vol * pow(10, -27)
     78 atom_lit = 9.03 * pow(10, 22)
     79 conc = float(Concentration)

NameError: name 'vol' is not defined

**Comment by pablo-arantes** [comment]
Hi @pramsland,

Sorry for the delay.
You have an issue on AMBER tleap, probably the atom name or other issue in your PDB file are creating some problems in the topology generation step. Can you please double-check your file and compare with our example file? 
This notebook was created to run glycan systems from GLYCAM server (https://glycam.org/#). Are you using a PDB file from GLYCAM? 

Thank you.
